name: Deb Build

on:
  repository_dispatch:

jobs:
  build_ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: nitanmarcel/waydroid-magisk
          path: waydroid-magisk
          submodules: true
          ref: main
      - name: Build Ubuntu Package
        uses: jiro4989/build-deb-action@v2
        with:
          package: waydroid-magisk
          package_root: .debpkg
          maintainer: Marcel Alexandru Nitan
          arch: all
      - name: Copy deb
        run: |
          cp .debpkg/*.deb ppa/
          rm .debpkg waydroid-magisk -rf
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Update and sign apt repository
        run: |
          dpkg-scanpackages --multiversion . > ppa/Packages
          gzip -k -f ubuntu/Packages
          apt-ftparchive release . > ppa/Release
          gpg --default-key "nitan.marcel@protonmail.com" -abs -o - ppa/Release > ppa/Release.gpg
          gpg --default-key "nitan.marcel@protonmail.com" --clearsign -o - ppa/Release > ppa/InRelease
      - name: Commit and push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          author_name: Marcel Alexandru Nitan
          author_email: nitan.marcel@protonmail.com
          message: "Update packages"
          branch: "repo"
